FROM gradle:7.6.1-jdk17 AS builder
WORKDIR /app
COPY --chown=gradle:gradle . .
RUN ./gradlew clean build -x test --no-daemon

FROM openjdk:17-jdk-slim
COPY --from=builder /app/build/libs/oauth2-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]